kafka:
  topic:
    name: pramod-avro-demo

spring:
  kafka:
    bootstrap-servers: "localhost:9092" # "172.24.48.1:9092"
    producer:
      keySerializer: "org.apache.kafka.common.serialization.StringSerializer"
      valueSerializer: "io.confluent.kafka.serializers.KafkaAvroSerializer"
      properties:
        schema:
          registry:
            url: "http://localhost:8081"  # "172.24.48.1:9092"
    consumer:
      group-id: "employee-group"
      keyDeserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      valueDeserializer: "io.confluent.kafka.serializers.KafkaAvroDeserializer"
      autoOffsetReset: "earliest"
      properties:
        schema:
          registry:
            url: "http://localhost:8081"  # "172.24.48.1:9092"
        specific:
          avro:
            reader: "true"